shop:
    resource: "@ShopBundle/Controller/"
    type:     annotation
    prefix:   /

#service:
#    resource: "@ServiceBundle/Controller/"
#    type:     annotation
#    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
